# Generated by Django 5.1.1 on 2024-12-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('fecha_pago', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('tarjeta_ultimos_digitos', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
