# Generated by Django 5.1.1 on 2024-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField()),
                ('pre_requisitos', models.ManyToManyField(blank=True, related_name='requisitos_para', to='cursos.curso')),
            ],
        ),
    ]
