# Generated by Django 5.1.1 on 2024-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
