# Generated by Django 5.1.1 on 2024-10-02 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
