# Generated by Django 5.1.1 on 2024-10-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_historialnotas'),
        ('estudiantes', '0008_alter_estudiante_codigo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historialnotas',
            unique_together={('estudiante', 'curso', 'semestre')},
        ),
    ]
