# Generated by Django 5.1.1 on 2024-10-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_historialnotas_unique_together_and_more'),
        ('estudiantes', '0008_alter_estudiante_codigo_and_more'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historialnotas',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historialnotas',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_notas', to='semestre.semestre'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='historialnotas',
            unique_together={('estudiante', 'curso', 'semestre')},
        ),
    ]
