# Generated by Django 5.1.1 on 2024-09-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_rename_matricula_estudiante_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_ingreso',
        ),
    ]
