# Generated by Django 5.1.1 on 2024-09-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_estudiante_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
