# Generated by Django 5.1.1 on 2024-09-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiante_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
    ]
