# Generated by Django 5.1.1 on 2024-09-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_informacionpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='base',
            field=models.CharField(max_length=20),
        ),
    ]
