# Generated by Django 5.1.1 on 2024-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_alter_estudiante_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
