# Generated by Django 5.1.1 on 2024-10-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('periodo', models.CharField(choices=[('I', 'Primero'), ('II', 'Segundo')], max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('año', 'periodo')},
            },
        ),
    ]
