# Generated by Django 5.1.1 on 2024-10-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0005_alter_historialnotas_unique_together'),
        ('estudiantes', '0008_alter_estudiante_codigo_and_more'),
        ('horarios', '0005_seccion_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='estudiantes.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_matriculados', to='matriculas.matricula')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.seccion')),
            ],
            options={
                'unique_together': {('matricula', 'curso')},
            },
        ),
    ]
