# Generated by Django 5.1.1 on 2024-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculacurso',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='fecha',
        ),
        migrations.AddField(
            model_name='matricula',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
