# Generated by Django 5.1.1 on 2024-10-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_seccion_semestre'),
        ('matriculas', '0004_alter_matricula_semestre_remove_matricula_activa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.seccion')),
            ],
            options={
                'unique_together': {('matricula', 'seccion')},
            },
        ),
    ]
