# Generated by Django 5.1.1 on 2024-10-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_historialnotas_unique_together'),
        ('horarios', '0002_horario_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='cupos',
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('cupos_totales', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
        migrations.AlterField(
            model_name='horario',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.seccion'),
        ),
    ]
