# Generated by Django 5.1.1 on 2024-10-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_historialnotas_unique_together'),
        ('horarios', '0003_remove_horario_cupos_seccion_alter_horario_seccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('curso', 'seccion', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
