# Generated by Django 5.1.1 on 2024-10-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_seccion_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='semestre',
        ),
    ]
