# Generated by Django 5.1.1 on 2024-10-09 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_remove_seccion_semestre'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='semestre.semestre'),
            preserve_default=False,
        ),
    ]
