# Generated by Django 5.1.1 on 2024-10-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_seccion_semestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('seccion', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
    ]
